package com.padas2.bitbucket.supportzip;

public enum  STATE {
    IDLE,
    SUPPORT_ZIP_CREATION_INITIATED,
    SUPPORT_ZIP_CREATION_FINISHED,
    SUPPORT_ZIP_DOWNLOAD_INITIATED,
    SUPPORT_ZIP_DOWNLOAD_FINISHED,
    SUPPORT_ZIP_UNZIPPING_INITIATED,
    SUPPORT_ZIP_UNZIPPING_FINISHED,
    UNZIPPED_DIR_FLATTENING_INITIATED,
    UNZIPPED_DIR_FLATTENING_FINISHED;
}
