package com.padas2.bitbucket.supportzip;

public enum  STATE {
    IDLE,
    BITBUCKET_SERVER_HEALTH_CHECK_INITIATED,
    BITBUCKET_SERVER_HEALTH_CHECK_FINISHED,
    SUPPORT_ZIP_CREATION_INITIATED,
    SUPPORT_ZIP_CREATION_FINISHED,
    SUPPORT_ZIP_DOWNLOAD_INITIATED,
    SUPPORT_ZIP_DOWNLOAD_FINISHED,
    SUPPORT_ZIP_UNZIPPING_INITIATED,
    SUPPORT_ZIP_UNZIPPING_FINISHED,
    UNZIPPED_DIR_FLATTENING_INITIATED,
    UNZIPPED_DIR_FLATTENING_FINISHED,
    CREDENTIALS_VALIDITY_CHECK_INITIATED,
    CREDENTIALS_VALIDITY_CHECK_FINISHED,
    CREDENTIALS_PERMISSION_CHECK_INITIATED,
    CREDENTIALS_PERMISSION_CHECK_FINISHED;
}
